Repository Retro-pong/Transcendence, pull requests merged in 2024-06, with the labels that each got.

#157 [Refactor] ErrorHandler 클래스명 변경
  frontend/src/pages/Friends.js
  frontend/src/pages/Login.js
  frontend/src/pages/Profile.js
  frontend/src/pages/game/CreateRoom.js
  frontend/src/pages/game/JoinRoom.js
  frontend/src/utils/ToastHandler.js
  frontend/src/utils/TokenManager.js
  frontend/src/utils/router.js
Labels: FE

#158 [Fix] regex 수정
  frontend/src/constants/Regex.js
  frontend/src/pages/Login.js
Labels: bug, FE

#159 [BE] 게임 app 시작
  backend/backend/settings.py
  backend/friends/admin.py
  backend/friends/models.py
  backend/game/__init__.py
  backend/game/admin.py
  backend/game/apps.py
  backend/game/consumers.py
  backend/game/migrations/__init__.py
  backend/game/models.py
  backend/game/modules.py
  backend/game/routing.py
  backend/game/serializers.py
  backend/game/tests.py
  backend/login/views.py
  backend/rooms/consumers.py
  backend/rooms/models.py
  backend/rooms/routing.py
  backend/users/serializers.py
  backend/users/tests.py
Labels: enhancement, BE

#162 [Refactor, Fix] router class 로 변경
  frontend/src/component/PageComponent.js
  frontend/src/index.js
  frontend/src/pages/Home.js
  frontend/src/pages/Login.js
  frontend/src/pages/game/CreateRoom.js
  frontend/src/utils/Router.js
  frontend/src/utils/TokenManager.js
  frontend/src/utils/router.js
Labels: bug, enhancement, FE

#163 160 be 1vs1 consumer
  backend/game/consumers.py
  backend/game/models.py
  backend/game/modules.py
  backend/rooms/models.py
  backend/users/serializers.py
Labels: BE

#169 [Feat] JWT middleware 추가
  backend/backend/asgi.py
  backend/backend/middleware.py
  backend/backend/settings.py
  backend/game/tests.py
  frontend/src/component/PageComponent.js
  frontend/src/constants/Regex.js
  frontend/src/index.js
  frontend/src/pages/Friends.js
  frontend/src/pages/Home.js
  frontend/src/pages/Login.js
  frontend/src/pages/Profile.js
  frontend/src/pages/game/CreateRoom.js
  frontend/src/pages/game/JoinRoom.js
  frontend/src/utils/Router.js
  frontend/src/utils/ToastHandler.js
  frontend/src/utils/TokenManager.js
  frontend/src/utils/router.js
Labels: enhancement, BE

#165 [Feat] env 추가
  frontend/src/utils/Fetch.js
  frontend/vite.config.js
Labels: enhancement, FE

#170 [BE]fix: game consumer result fix
  backend/game/consumers.py
  backend/game/modules.py
  backend/rooms/consumers.py
  backend/rooms/routing.py
Labels: BE

#168 [Fix] 공 히트 시 속도 수정
  frontend/src/utils/game/game.js
Labels: bug, FE

#172 166 be game 대기실 consumer
  backend/backend/asgi.py
  backend/backend/middleware.py
  backend/backend/settings.py
  backend/game/consumers.py
  backend/requirements.txt
  backend/rooms/consumers.py
  backend/rooms/tests.py
Labels: BE

#173 [BE] [Refactor] http status code
  backend/friends/models.py
  backend/friends/views.py
  backend/login/views.py
  backend/users/views.py
Labels: BE

#174 consumer test 수정 및 redis, daphne 추가중
  .gitignore
  backend/Dockerfile
  backend/backend/asgi.py
  backend/backend/middleware.py
  backend/backend/settings.py
  backend/cmd.sh
  backend/game/consumers.py
  backend/game/modules.py
  backend/requirements.txt
  backend/rooms/consumers.py
  backend/rooms/tests.py
  nginx/server.conf
Labels: BE

#175 [BE]feat: room, login consumer add, test complete
  backend/backend/asgi.py
  backend/backend/middleware.py
  backend/game/consumers.py
  backend/login/consumers.py
  backend/login/routing.py
  backend/login/tests.py
  backend/rooms/consumers.py
  backend/rooms/tests.py
  backend/users/models.py
Labels: BE

#176 [Feat] big merge
  .gitignore
  backend/Dockerfile
  backend/backend/asgi.py
  backend/backend/middleware.py
  backend/backend/settings.py
  backend/cmd.sh
  backend/friends/admin.py
  backend/friends/models.py
  backend/friends/views.py
  backend/game/__init__.py
  backend/game/admin.py
  backend/game/apps.py
  backend/game/consumers.py
  backend/game/migrations/__init__.py
  backend/game/models.py
  backend/game/modules.py
  backend/game/routing.py
  backend/game/serializers.py
  backend/game/tests.py
  backend/login/consumers.py
  backend/login/routing.py
  backend/login/tests.py
  backend/login/views.py
  backend/requirements.txt
  backend/rooms/consumers.py
  backend/rooms/models.py
  backend/rooms/routing.py
  backend/rooms/tests.py
  backend/users/models.py
  backend/users/serializers.py
  backend/users/tests.py
  backend/users/views.py
  nginx/server.conf
Labels: enhancement, BE

#177 [Fix] 42 intra key 재발급
  backend/.env
  backend/login/views.py
Labels: bug, BE

#180 [BE]Fix: Jwtmiddleware fix
  backend/backend/asgi.py
  backend/backend/middleware.py
  backend/login/consumers.py
  backend/login/tests.py
Labels: bug, BE

#181 [Test] http status 수정
  backend/friends/models.py
  backend/friends/tests.py
  backend/friends/views.py
Labels: enhancement, BE

#182 [Test] http 응답 코드 수정
  backend/friends/models.py
  backend/friends/tests.py
  backend/friends/views.py
Labels: enhancement, BE

#183 [BE] redis install
  backend/Dockerfile
  backend/cmd.sh
Labels: bug, BE

#184 [Feat] 로그인 소켓 연결
  frontend/src/utils/SocketManager.js
  frontend/src/utils/TokenManager.js
Labels: enhancement, FE

#187 [BE]fix: room, login consumer fix
  backend/login/consumers.py
  backend/login/tests.py
  backend/rooms/consumers.py
  backend/rooms/tests.py
Labels: BE

#188 [Test] login test 수정
  backend/login/tests.py
Labels: BE

#190 [Feat] 응답 에러 코드 추가
  frontend/src/pages/Friends.js
  frontend/src/pages/Login.js
  frontend/src/pages/Profile.js
  frontend/src/utils/Fetch.js
  frontend/src/utils/TokenManager.js
Labels: enhancement, FE

#192 191 be normal game consumer
  backend/game/consumers.py
  backend/game/modules.py
  backend/game/routing.py
  backend/game/tests.py
  backend/rooms/consumers.py
  backend/rooms/models.py
  backend/rooms/tests.py
  frontend/src/pages/Friends.js
  frontend/src/pages/Login.js
  frontend/src/pages/Profile.js
  frontend/src/utils/Fetch.js
  frontend/src/utils/TokenManager.js
Labels: enhancement, BE

#193 [BE] [Feat] 대기실, 일대일매치 구현
  backend/game/consumers.py
  backend/game/modules.py
  backend/game/routing.py
  backend/game/tests.py
  backend/rooms/consumers.py
  backend/rooms/models.py
  backend/rooms/tests.py
Labels: enhancement, BE

#194 [BE]fix:create room response fix
  backend/rooms/views.py
Labels: BE

#197 [BE]fix: room send_json fix
  backend/rooms/consumers.py
Labels: bug, BE

#198 [BE] [Feat] tournament room
  backend/backend/settings.py
  backend/rooms/consumers.py
  backend/rooms/routing.py
Labels: enhancement, BE

#199 [BE]fix: game module error fix
  backend/game/modules.py
  backend/game/tests.py
Labels: bug, BE

#196 [TEST] 게임 대기실 소켓 연결
  frontend/src/component/card/PlayerCard.js
  frontend/src/pages/game/CreateRoom.js
  frontend/src/pages/game/JoinRoom.js
  frontend/src/pages/game/WaitingRoom.js
  frontend/src/utils/SocketManager.js
Labels: enhancement, FE

#200 [BE] [Fix] 대기실 대거 수정
  backend/backend/settings.py
  backend/rooms/consumers.py
  backend/rooms/routing.py
  backend/rooms/tests.py
Labels: bug, BE

#201 [Feat] tournament room
  backend/rooms/consumers.py
  backend/rooms/routing.py
  backend/rooms/tests.py
Labels: enhancement, BE

#202 [BE]fix: add image path in consumer response
  backend/rooms/consumers.py
Labels: bug, BE

#203 [BE] Fix: 대기실 중복 입장 불가
  backend/rooms/consumers.py
Labels: bug, BE

#204 [Feat] 게임 대기실 소켓 연결
  frontend/src/component/card/PlayerCard.js
  frontend/src/pages/game/CreateRoom.js
  frontend/src/pages/game/Game.js
  frontend/src/pages/game/JoinRoom.js
  frontend/src/pages/game/WaitingRoom.js
Labels: enhancement, FE

#205 [Fix] 게임 대기실 소켓 연결
  frontend/src/pages/game/JoinRoom.js
  frontend/src/pages/game/WaitingRoom.js
Labels: bug, FE

#207 189 feat tournament room
  backend/backend/middleware.py
  backend/rooms/consumers.py
Labels: enhancement, BE

#208 [Fix] roll back
  backend/backend/middleware.py
  backend/rooms/consumers.py
Labels: bug, BE

#209 Backend
  backend/backend/middleware.py
  backend/rooms/consumers.py
Labels: BE

#206 [Feat, Refactor] 게임 소켓 연결
  frontend/src/component/modal/ModalComponent.js
  frontend/src/index.html
  frontend/src/pages/game/PlayGame.js
  frontend/src/utils/Router.js
  frontend/src/utils/game/GameManager.js
  frontend/src/utils/game/eventHandler.js
  frontend/src/utils/game/eventHandler/localEventHandler.js
  frontend/src/utils/game/eventHandler/multiEventHandler.js
  frontend/src/utils/game/game.js
  frontend/src/utils/game/localGame.js
  frontend/src/utils/game/render/rendering.js
  frontend/src/utils/game/render/resizeRendererToDisplaySize.js
  frontend/src/utils/game/setting/cameraSetting.js
  frontend/src/utils/game/setting/createGameObject.js
  frontend/src/utils/game/setting/createMap.js
  frontend/src/utils/game/setting/sceneSetting.js
  frontend/src/utils/game/utils/checkPaddleHit.js
  frontend/src/utils/game/utils/gameUtils.js
  frontend/src/utils/game/utils/hitChangeColor.js
  frontend/src/utils/game/utils/localGameStartSetting.js
Labels: enhancement, FE

#210 [BE]fix: game logic refactor
  backend/game/consumers.py
  backend/game/modules.py
  backend/rooms/consumers.py
Labels: BE

#215 [Chore] fixed format
  backend/game/consumers.py
  backend/game/modules.py
  backend/game/routing.py
  backend/game/tests.py
  backend/rooms/consumers.py
Labels: BE

#218 [BE]fix: game consumer response fix
  backend/game/consumers.py
  backend/game/modules.py
  backend/users/tests.py
Labels: bug, BE

#214 [Feat] 게임 소켓 에러 처리
  frontend/src/pages/game/PlayGame.js
  frontend/src/utils/Router.js
  frontend/src/utils/game/GameManager.js
  frontend/src/utils/game/eventHandler/localEventHandler.js
  frontend/src/utils/game/eventHandler/multiEventHandler.js
  frontend/src/utils/game/localGame.js
  frontend/src/utils/game/render/rendering.js
  frontend/src/utils/game/render/resizeRendererToDisplaySize.js
  frontend/src/utils/game/utils/checkPaddleHit.js
  frontend/src/utils/game/utils/hitChangeColor.js
  frontend/src/utils/game/utils/localGameStartSetting.js
Labels: enhancement, FE

#220 [Fix] normal game, tournament room 에러 처리
  backend/game/consumers.py
  backend/rooms/consumers.py
  backend/rooms/tests.py
Labels: bug, BE

#223 [BE]fix:game result model, test fix"
  backend/game/consumers.py
  backend/game/models.py
  backend/game/serializers.py
  backend/users/serializers.py
  backend/users/tests.py
Labels: bug, BE

#225 224 fix game login 객체 관리 수정
  backend/backend/middleware.py
  backend/game/consumers.py
  backend/game/modules.py
Labels: BE

#219 [Feat] 프로필 배틀 히스토리 조회
  frontend/src/component/PageComponent.js
  frontend/src/component/contents/BattleHistory.js
  frontend/src/component/contents/GameRoomInfo.js
  frontend/src/pages/Profile.js
  frontend/src/pages/game/WaitingRoom.js
  frontend/src/scss/colors.scss
  frontend/src/scss/variables.scss
  frontend/src/utils/Router.js
Labels: enhancement, FE

#226 [Fix] 게임 플레이 페이지 에러 처리
  frontend/src/index.html
  frontend/src/pages/game/PlayGame.js
  frontend/src/pages/game/WaitingRoom.js
  frontend/src/utils/Router.js
  frontend/src/utils/game/GameManager.js
Labels: bug, FE

#229 [Feat] tournament game consumer 추가
  backend/game/consumers.py
  backend/game/routing.py
  backend/rooms/consumers.py
  backend/rooms/tests.py
Labels: enhancement, BE

#233 [Feat] tournament game consumer 추가
  backend/game/consumers.py
  backend/game/models.py
  backend/game/routing.py
  backend/rooms/consumers.py
  backend/rooms/tests.py
Labels: enhancement, BE

#231 [Fix] 게임 소켓 에러메세지 처리 수정
  frontend/src/component/PageComponent.js
  frontend/src/pages/game/PlayGame.js
  frontend/src/utils/Router.js
  frontend/src/utils/game/GameManager.js
Labels: bug, FE

#232 [Fix] Fetch 응답 수정
  frontend/src/pages/Friends.js
  frontend/src/pages/Login.js
  frontend/src/pages/Profile.js
  frontend/src/scss/styles.scss
  frontend/src/utils/Fetch.js
  frontend/src/utils/TokenManager.js
Labels: bug, FE

#236 [Feat] 게임 매뉴얼 추가
  frontend/src/component/contents/GameManual.js
  frontend/src/pages/game/Game.js
  frontend/src/pages/game/WaitingRoom.js
  frontend/src/scss/styles.scss
Labels: enhancement, FE

#242 [BE]fix: room consumer 수정사항 반영
  backend/game/routing.py
  backend/game/tests.py
  backend/rooms/consumers.py
  backend/rooms/tests.py
Labels: bug, BE

#238 [Feat] 로컬 게임 설정, 모달 추가
  frontend/src/pages/game/PlayGame.js
  frontend/src/utils/game/GameManager.js
  frontend/src/utils/game/localGame.js
  frontend/src/utils/game/setting/createGameObject.js
  frontend/src/utils/game/setting/localGameCustomSetting.js
Labels: enhancement, FE

#241 [Feat] 멀티 게임 닉네임 설정
  frontend/src/pages/game/PlayGame.js
Labels: enhancement, FE

#243 [Fix] 대기실 소켓 에러 처리
  frontend/src/index.js
  frontend/src/pages/game/CreateRoom.js
  frontend/src/pages/game/WaitingRoom.js
  frontend/src/utils/Router.js
  frontend/src/utils/SocketManager.js
Labels: bug, FE

#246 244 feat tournament consumer 구현
  backend/game/consumers.py
  backend/game/modules.py
  backend/game/routing.py
  backend/game/tests.py
  backend/rooms/consumers.py
  backend/rooms/tests.py
Labels: BE

#248 247 feat postgre db 연결
  backend/backend/settings.py
  backend/cmd.sh
  backend/game/consumers.py
  backend/game/modules.py
  backend/game/routing.py
  backend/game/tests.py
  backend/requirements.txt
  backend/rooms/consumers.py
  backend/rooms/tests.py
  docker-compose.yml
Labels: BE

#249 Chore: main 브랜치 backend에 병합
  backend/backend/settings.py
  backend/cmd.sh
  backend/game/consumers.py
  backend/requirements.txt
  docker-compose.yml
Labels: enhancement, BE

#253 [BE]fix: semi final consumer response fix
  backend/game/consumers.py
  backend/game/modules.py
  backend/game/tests.py
Labels: BE

#255 [Docs] db erd 정리
  README.md
  backend/backend/settings.py
  backend/game/consumers.py
  backend/users/models.py
  img/DB_ERD.png
Labels: documentation, BE

#256 [BE]fix: cors error fix
  backend/.env
  backend/backend/settings.py
  backend/requirements.txt
  frontend/src/component/button/LoginPageButtons.js
Labels: BE

#260 [BE]fix:semi consumer response fix
  backend/game/consumers.py
  backend/game/modules.py
  backend/game/tests.py
Labels: bug, BE

#261 [Fix] 대기실 현재 인원 업데이트
  backend/friends/views.py
  backend/rooms/consumers.py
  backend/rooms/views.py
  frontend/.env
Labels: BE

#264 [BE]fix: friend response fix
  backend/friends/tests.py
  backend/friends/views.py
Labels: BE

#265 [Chore] 메일 인증 임시 제거
  backend/login/utils.py
Labels: BE

#267 [Fix] game consumer time out add
  backend/game/consumers.py
  backend/game/modules.py
  backend/game/tests.py
  backend/rooms/consumers.py
Labels: bug, BE

#269 [BE]fix: game consumer timeout method fix
  backend/game/consumers.py
  backend/game/tests.py
Labels: bug, BE

#270 [BE]fix:game consumer timeout fix
  backend/game/consumers.py
  backend/game/tests.py
  frontend/.env
Labels: bug, BE

#271 [Fix] 대기실 소켓 에러
  .gitignore
  frontend/.env
  frontend/src/component/contents/BattleHistory.js
  frontend/src/pages/game/Game.js
  frontend/src/pages/game/PlayGame.js
  frontend/src/pages/game/WaitingRoom.js
  frontend/src/utils/SocketManager.js
Labels: bug, FE

#275 [Fix] 게임 소켓 토너먼트 부분 수정
  frontend/src/component/modal/ModalComponent.js
  frontend/src/pages/game/PlayGame.js
Labels: bug, enhancement, design

#280 [Fix] user management errors
  backend/login/serializers.py
  backend/login/views.py
Labels: enhancement, BE

#276 [Design] UI 피드백 반영 및 로그인 화면 버그 수정
  frontend/src/component/button/LoginPageButtons.js
  frontend/src/component/modal/ModalComponent.js
  frontend/src/pages/Login.js
  frontend/src/pages/Profile.js
  frontend/src/pages/game/WaitingRoom.js
  frontend/src/scss/styles.scss
  frontend/src/utils/SocketManager.js
Labels: bug, FE, design

#279 [Fix] url 직접접근 막기 및 게임 페이지 수정
  frontend/src/index.js
  frontend/src/pages/game/PlayGame.js
Labels: bug, enhancement, FE

#282 [Fix] tournament test
  backend/game/consumers.py
  frontend/src/index.js
  frontend/src/pages/Login.js
  frontend/src/pages/game/CreateRoom.js
  frontend/src/pages/game/PlayGame.js
  frontend/src/pages/game/WaitingRoom.js
  frontend/src/utils/SocketManager.js
Labels: bug, FE, BE

#283 [BE]fix: tournament conusmer fix, postgre 주석 해제
  backend/backend/settings.py
  backend/game/consumers.py
  docker-compose.yml
Labels: bug, BE

#285 [BE]fix: room consumer player number logic fix
  .gitignore
  backend/.env
  backend/game/consumers.py
  backend/game/tests.py
  backend/rooms/consumers.py
  backend/rooms/tests.py
  docker-compose.yml
Labels: bug, BE

#290 [BE]fix: friend request user fix
  backend/friends/models.py
  backend/friends/serializers.py
  backend/friends/tests.py
  backend/friends/views.py
  img/DB_ERD.png
Labels: BE

#293 [Design] 게임 생성 페이지 수정
  frontend/src/component/form/CreateRoomForm.js
  frontend/src/component/form/CreateRoomFormItem.js
  frontend/src/pages/game/CreateRoom.js
Labels: bug, enhancement, FE, design

#296 [Fix] 로컬플레이 에러 수정
  frontend/src/utils/Router.js
  frontend/src/utils/SocketManager.js
  frontend/src/utils/game/GameManager.js
  frontend/src/utils/game/localGame.js
Labels: bug, enhancement, FE

#297 [Feat] 친구 배틀 히스토리 조회, bgm 추가
  frontend/public/bgm/bgm1.mp3
  frontend/public/icons/volume-mute.svg
  frontend/public/icons/volume-up.svg
  frontend/src/component/card/FriendInfoCard.js
  frontend/src/component/contents/BattleHistory.js
  frontend/src/index.html
  frontend/src/index.js
  frontend/src/pages/Friends.js
  frontend/src/scss/styles.scss
  frontend/src/utils/musicController.js
  frontend/vite.config.js
Labels: enhancement, FE
