Repository Retro-pong/Transcendence, pull requests merged in 2024-08, with the labels that each got.

#315 [Chore] env 정리
  backend/backend/settings.py
Labels: BE

#316 [Chore] 장고 setting 변경
  backend/backend/settings.py
Labels: BE

#317 [Fix] 친구 검색 시와 신청 시 닉네임이 다를 경우
  backend/friends/views.py
Labels: bug, BE

#318 [FIX] frontend 설정 추가 및 backend 이메일 로그인 수정
  backend/login/views.py
  frontend/src/index.html
  frontend/vite.config.js
Labels: FE, BE

#321 [Docs] readme 업데이트
  README.md
Labels: documentation

#322 [Fix] 프론트엔드 bind mount 수정
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
Labels: bug, FE
