Repository Retro-pong/Transcendence, pull requests merged in 2024-07, with the labels that each got.

#299 [Design] 친구 검색 목록 css 수정
  frontend/src/component/contents/FriendSearch.js
  frontend/src/component/contents/FriendSearchListItem.js
  frontend/src/pages/Friends.js
Labels: bug, FE, design

#300 [Fix] 프론트 에러
  frontend/src/utils/Router.js
  frontend/src/utils/SocketManager.js
Labels: bug, FE

#302 [Fix] 로컬 게임 뒤로 가기 에러
  frontend/src/pages/game/PlayGame.js
  frontend/src/utils/game/GameManager.js
Labels: bug, FE, design

#306 305 fix backend 수정 사항
  backend/cmd.sh
  backend/game/modules.py
  docker-compose.yml
  postgres/Dockerfile
Labels: BE

#304 [Fix] 프론트 수정사항
  frontend/src/component/card/FriendInfoCard.js
  frontend/src/component/form/CreateRoomForm.js
  frontend/src/pages/game/CreateRoom.js
  frontend/src/pages/game/PlayGame.js
  frontend/src/utils/game/GameManager.js
  frontend/src/utils/game/localGame.js
Labels: bug, enhancement, FE

#286 [Build] https 연결 (Merge X)
  backend/backend/settings.py
  backend/login/tests.py
  backend/login/utils.py
  backend/login/views.py
  backend/users/views.py
  docker-compose.yml
  frontend/Dockerfile
  frontend/db.json
  frontend/package-lock.json
  frontend/package.json
  frontend/routes.json
  frontend/src/pages/Friends.js
  frontend/src/pages/Home.js
  frontend/src/pages/Login.js
  frontend/src/pages/game/CreateRoom.js
  frontend/src/pages/game/PlayGame.js
  frontend/src/pages/game/WaitingRoom.js
  frontend/src/utils/Fetch.js
  frontend/src/utils/SocketManager.js
  frontend/vite.config.js
  nginx/Dockerfile
  nginx/init.sh
  nginx/server.conf
Labels: enhancement, FE, BE

#309 [Fix] exception handling
  backend/friends/models.py
  backend/friends/views.py
  backend/game/consumers.py
  backend/login/consumers.py
  backend/login/views.py
  backend/rooms/views.py
  backend/users/views.py
Labels: BE

#313 312 fix duplicate login
  backend/game/consumers.py
  backend/game/modules.py
  backend/rooms/consumers.py
Labels: bug, BE

#311 [Feat] 멀티게임 점수 딴 직후 화면 요소 추가
  frontend/src/component/form/CreateRoomForm.js
  frontend/src/pages/game/PlayGame.js
Labels: bug, enhancement, FE
