Repository Retro-pong/Transcendence, pull requests merged in 2024-05, with the labels that each got.

#12 [FEAT] 회원가입 모달 기본 레이아웃
  frontend/src/component/PageComponent.js
  frontend/src/component/button/OpenModalButton.js
  frontend/src/component/form/RegisterForm.js
  frontend/src/component/form/RegisterFormItem.js
  frontend/src/component/modal/ModalComponent.js
  frontend/src/index.js
  frontend/src/pages/Login.js
  frontend/src/scss/custom_utilities.scss
  frontend/src/scss/font.scss
  frontend/src/scss/styles.scss
Labels: enhancement, FE

#14 [FIX] 배경 수정
  frontend/src/background/background.js
  frontend/src/index.html
  frontend/src/scss/background(v1).scss
  frontend/src/scss/background(v2).scss
  frontend/src/scss/background.scss
  frontend/src/scss/styles.scss
Labels: bug, FE

#22 [DESIGN] 친구대기, 추가 모달 레이아웃
  frontend/src/component/button/LoginPageButtons.js
  frontend/src/component/contents/FriendSearch.js
  frontend/src/component/contents/FriendSearchListItem.js
  frontend/src/component/contents/FriendWaitList.js
  frontend/src/component/contents/FriendWaitListItem.js
  frontend/src/component/modal/ModalComponent.js
  frontend/src/component/navigation/NavBar.js
  frontend/src/index.js
  frontend/src/pages/Friends.js
  frontend/src/pages/Login.js
  frontend/src/scss/custom_utilities.scss
  frontend/src/scss/styles.scss
Labels: FE, design

#25 [Feat] 친구 페이지 카드 컴포넌트 구현
  frontend/db.json
  frontend/package-lock.json
  frontend/package.json
  frontend/server.js
  frontend/src/component/card/FriendInfoCard.js
  frontend/src/pages/Friends.js
  frontend/src/scss/colors.scss
  frontend/src/scss/styles.scss
  frontend/src/utils/initTooltip.js
Labels: enhancement, FE

#29 [Design] 대기실 화면 레이아웃
  frontend/src/component/navigation/NavBar.js
  frontend/src/component/navigation/NavLink.js
  frontend/src/index.js
  frontend/src/pages/Game.js
  frontend/src/pages/Home.js
  frontend/src/pages/game/CreateRoom.js
  frontend/src/pages/game/Game.js
  frontend/src/pages/game/JoinRoom.js
  frontend/src/scss/styles.scss
Labels: FE, design

#32 [Feat] 2FA 로그인 기능 구현
  docker-compose.yml
  frontend/.eslintrc.js
  frontend/Dockerfile
  frontend/db.json
  frontend/package-lock.json
  frontend/package.json
  frontend/routes.json
  frontend/src/component/form/LoginForm.js
  frontend/src/component/modal/ModalComponent.js
  frontend/src/component/toast/ToastComponent.js
  frontend/src/constants/Regex.js
  frontend/src/index.js
  frontend/src/pages/Friends.js
  frontend/src/pages/Login.js
  frontend/src/scss/colors.scss
  frontend/src/scss/styles.scss
  frontend/src/scss/variables.scss
  frontend/src/utils/Fetch.js
  frontend/src/utils/TokenManager.js
  frontend/src/utils/router.js
Labels: enhancement, FE

#34 [DESIGN] 유저 프로필 페이지 레이아웃
  frontend/db.json
  frontend/src/component/contents/EditProfile.js
  frontend/src/component/contents/UserProfile.js
  frontend/src/component/contents/UserProfileBattleHistory.js
  frontend/src/component/contents/UserProfileInfo.js
  frontend/src/pages/Profile.js
  frontend/src/scss/styles.scss
Labels: FE, design

#30 [Feat] [Login] auth
  .gitignore
  backend/.env
  backend/Dockerfile
  backend/backend/__init__.py
  backend/backend/asgi.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/backend/wsgi.py
  backend/cmd.sh
  backend/init.sh
  backend/login/__init__.py
  backend/login/admin.py
  backend/login/apps.py
  backend/login/migrations/__init__.py
  backend/login/models.py
  backend/login/serializers.py
  backend/login/tests.py
  backend/login/urls.py
  backend/login/utils.py
  backend/login/views.py
  backend/manage.py
  backend/media/images/default_image.jpeg
  backend/requirements.txt
  backend/users/__init__.py
  backend/users/admin.py
  backend/users/apps.py
  backend/users/migrations/0001_initial.py
  backend/users/migrations/0002_alter_user_email_alter_user_is_active_and_more.py
  backend/users/migrations/__init__.py
  backend/users/models.py
  backend/users/tests.py
  backend/users/views.py
  img/DB_ERD.png
Labels: enhancement, BE

#36 [FEAT] 회원가입 기능
  frontend/src/component/button/LoginPageButtons.js
  frontend/src/component/form/RegisterForm.js
  frontend/src/component/modal/ModalComponent.js
  frontend/src/constants/Regex.js
  frontend/src/pages/Login.js
Labels: enhancement, FE

#39 [Feat] 친구 모달 내부 기능
  frontend/db.json
  frontend/src/component/button/FriendPageButtons.js
  frontend/src/component/contents/FriendSearch.js
  frontend/src/component/contents/FriendSearchListItem.js
  frontend/src/component/contents/FriendWaitList.js
  frontend/src/component/contents/FriendWaitListItem.js
  frontend/src/pages/Friends.js
  frontend/src/scss/styles.scss
  frontend/src/utils/debounce.js
Labels: enhancement, FE

#42 [Feat] nginx 프론트 연결
  Makefile
  docker-compose.yml
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  nginx/Dockerfile
  nginx/server.conf
Labels: enhancement, FE

#43 [Fix] 로그인페이지 접근 제한
  frontend/src/utils/router.js
Labels: bug, FE

#48 [Design] 게임 대기실 페이지 레이아웃
  frontend/src/component/card/PlayerCard.js
  frontend/src/component/contents/GameManual.js
  frontend/src/pages/game/JoinRoom.js
  frontend/src/pages/game/WaitingRoom.js
  frontend/src/scss/styles.scss
Labels: FE, design

#46 [Design, Feat] create room 레이아웃 및 기본 기능
  frontend/public/img/bg.jpeg
  frontend/public/img/map_futuristic_horizon.jpg
  frontend/public/img/map_mountain.jpg
  frontend/public/img/map_pixel_rain.jpg
  frontend/src/component/button/BasicButton.js
  frontend/src/component/form/CreateRoomForm.js
  frontend/src/component/form/CreateRoomFormItem.js
  frontend/src/constants/Regex.js
  frontend/src/pages/Login.js
  frontend/src/pages/game/CreateRoom.js
  frontend/src/scss/colors.scss
  frontend/src/scss/styles.scss
  frontend/src/utils/router.js
Labels: enhancement, FE, design

#50 [Fix] BasicButton 컴포넌트 스타일 수정
  frontend/src/component/button/BasicButton.js
  frontend/src/component/button/LoginPageButtons.js
  frontend/src/pages/game/JoinRoom.js
  frontend/src/scss/styles.scss
Labels: bug, FE

#51 Backend
  backend/.env
  backend/backend/settings.py
  backend/backend/urls.py
  backend/login/urls.py
  backend/login/utils.py
  backend/login/views.py
  backend/requirements.txt
  backend/users/models.py
  backend/users/serializers.py
  backend/users/urls.py
  backend/users/views.py
Labels: enhancement, BE

#52 Backend merge
  backend/login/views.py
  docker-compose.yml
  nginx/server.conf
Labels: BE

#54 [FIX] nginx config backend proxy 설정 추가
  nginx/server.conf
Labels: bug, FE, BE

#56 Backend
  backend/.env
  backend/login/serializers.py
  backend/login/urls.py
  backend/login/utils.py
  backend/login/views.py
Labels: enhancement, BE

#58 16 feat user user profile api
  backend/users/models.py
  backend/users/views.py
  nginx/server.conf
Labels: enhancement, BE

#62 Backend
  backend/backend/settings.py
  backend/login/views.py
  backend/users/models.py
  backend/users/views.py
Labels: bug, BE

#65 [Feat, Test] 로그아웃 api 연결 및 42 로그인 테스트
  backend/.env
  frontend/src/component/button/LoginPageButtons.js
  frontend/src/component/navigation/NavBar.js
  frontend/src/index.html
  frontend/src/index.js
  frontend/src/pages/Login.js
  frontend/src/utils/TokenManager.js
  frontend/src/utils/router.js
Labels: bug, enhancement, FE

#67 [BE] Fix: oauth callback 반환값 변경
  backend/login/views.py
  backend/users/views.py
Labels: bug, BE

#68 [Fix] oauth, logout 수정
  backend/login/views.py
Labels: bug, BE

#66 [Fix] 이메일 인증 모달 수정
  frontend/src/pages/Login.js
Labels: bug, FE

#69 [Fix] Fetch credentials 수정
  frontend/src/pages/Login.js
  frontend/src/scss/styles.scss
  frontend/src/utils/Fetch.js
  frontend/src/utils/TokenManager.js
Labels: bug, FE

#71 [Feat] reissueAccessToken 추가
  frontend/src/utils/TokenManager.js
Labels: enhancement, FE

#72 [Fix] JWT cookie 조건 수정, logout 정식 구현
  backend/login/utils.py
  backend/login/views.py
Labels: bug, BE

#74 [Feat] nginx ssl/tls 추가
  docker-compose.yml
  frontend/Dockerfile
  nginx/Dockerfile
  nginx/init.sh
  nginx/server.conf
Labels: enhancement

#76 [Fix] [Login] oauth 수정
  backend/.env
  backend/Dockerfile
  backend/backend/settings.py
  backend/login/tests.py
  backend/login/views.py
Labels: bug, BE

#77 [BE] Chore: merge with main
  backend/Dockerfile
  backend/backend/settings.py
  backend/login/tests.py
  backend/login/views.py
  docker-compose.yml
  frontend/Dockerfile
  nginx/Dockerfile
  nginx/init.sh
  nginx/server.conf
Labels: BE

#79 [Feat, Fix] 로그인 관련 api 연결 및 버그 수정
  backend/.env
  backend/login/views.py
  docker-compose.yml
  frontend/Dockerfile
  frontend/src/component/form/LoginForm.js
  frontend/src/index.js
  frontend/src/pages/Home.js
  frontend/src/pages/Login.js
  frontend/src/utils/Fetch.js
  frontend/src/utils/TokenManager.js
  frontend/src/utils/router.js
  nginx/Dockerfile
  nginx/server.conf
Labels: bug, enhancement, FE

#85 [BE] Fix: refrest token view fix
  backend/backend/settings.py
  backend/login/views.py
Labels: bug, BE

#86 [Fix] [Login] 전면 수정
  backend/.DS_Store
  backend/images/test_image.jpg
  backend/login/serializers.py
  backend/login/utils.py
  backend/login/views.py
  backend/media/test/test_image.jpg
  backend/users/models.py
  backend/users/tests.py
  backend/users/views.py
Labels: bug, BE

#87 [Fix] 레이아웃 비율 수정
  frontend/src/component/button/LoginPageButtons.js
  frontend/src/component/form/RegisterFormItem.js
  frontend/src/component/text/Header.js
  frontend/src/index.html
  frontend/src/pages/Login.js
  frontend/src/pages/game/Game.js
  frontend/src/scss/custom_utilities.scss
  frontend/src/scss/styles.scss
  frontend/src/scss/variables.scss
  frontend/src/utils/router.js
Labels: bug, FE, design

#88 [Fix] 로그아웃 여러 번 요청하는 문제, 로딩 처리
  frontend/src/index.html
  frontend/src/index.js
  frontend/src/pages/Login.js
  frontend/src/scss/styles.scss
  frontend/src/utils/Fetch.js
  frontend/src/utils/TokenManager.js
  frontend/src/utils/router.js
Labels: bug, enhancement, FE

#92 78 feat profile friend api 구현
  backend/backend/settings.py
  backend/backend/urls.py
  backend/friends/__init__.py
  backend/friends/admin.py
  backend/friends/apps.py
  backend/friends/models.py
  backend/friends/serializers.py
  backend/friends/tests.py
  backend/friends/urls.py
  backend/friends/views.py
  backend/users/tests.py
Labels: enhancement, BE

#95 94 feat game rooms api
  backend/backend/settings.py
  backend/backend/urls.py
  backend/rooms/__init__.py
  backend/rooms/admin.py
  backend/rooms/apps.py
  backend/rooms/models.py
  backend/rooms/serializers.py
  backend/rooms/tests.py
  backend/rooms/urls.py
  backend/rooms/views.py
  backend/users/serializers.py
Labels: enhancement, BE

#93 [Feat, Design] 게임 페이지 및 기본 오브젝트 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/public/object/low poly vhs textures.png
  frontend/public/object/tablePing.bin
  frontend/public/object/tablePing.gltf
  frontend/src/index.html
  frontend/src/pages/game/PlayGame.js
  frontend/src/scss/styles.scss
  frontend/src/utils/game.js
  frontend/src/utils/router.js
Labels: enhancement, FE, design

#96 [BE] Feat/Test: 방 리스트 DB 추가, 로그인/로그아웃 테스트 완료
  .gitignore
  backend/.DS_Store
  backend/backend/settings.py
  backend/backend/urls.py
  backend/friends/__init__.py
  backend/friends/admin.py
  backend/friends/apps.py
  backend/friends/models.py
  backend/friends/serializers.py
  backend/friends/tests.py
  backend/friends/urls.py
  backend/friends/views.py
  backend/login/tests.py
  backend/login/urls.py
  backend/login/views.py
  backend/rooms/__init__.py
  backend/rooms/admin.py
  backend/rooms/apps.py
  backend/rooms/models.py
  backend/rooms/serializers.py
  backend/rooms/tests.py
  backend/rooms/urls.py
  backend/rooms/views.py
  backend/users/serializers.py
  backend/users/tests.py
Labels: enhancement, BE

#99 [BE] Fix: swagger error fix
  backend/friends/urls.py
  backend/friends/views.py
Labels: bug, BE

#103 [BE] Fix: swagger fix, room api 분리
  backend/friends/views.py
  backend/rooms/models.py
  backend/rooms/tests.py
  backend/rooms/urls.py
  backend/rooms/views.py
  backend/users/models.py
Labels: enhancement, BE

#104 Fix git ignore fix
  backend/friends/migrations/__init__.py
  backend/rooms/migrations/__init__.py
  backend/users/migrations/0001_initial.py
  backend/users/migrations/0002_alter_user_email_alter_user_is_active_and_more.py
Labels: bug, BE

#107 Backend
  backend/friends/views.py
  backend/login/views.py
  backend/users/models.py
Labels: bug, BE

#109 [BE]Feat: create superuser method add
  backend/friends/admin.py
  backend/rooms/admin.py
  backend/users/models.py
Labels: enhancement, BE

#110 [BE]Chore: admin id add
  backend/cmd.sh
Labels: BE

#108 [Feat] friends 조회 api 연결 및 페이지네이션 추가
  frontend/db.json
  frontend/public/img/favicon.ico
  frontend/src/component/PageComponent.js
  frontend/src/component/button/BasicButton.js
  frontend/src/component/button/FriendPageButtons.js
  frontend/src/component/card/FriendInfoCard.js
  frontend/src/component/navigation/Pagination.js
  frontend/src/index.html
  frontend/src/pages/Friends.js
  frontend/src/pages/game/JoinRoom.js
  frontend/src/scss/custom_utilities.scss
  frontend/src/utils/Fetch.js
  frontend/src/utils/initTooltip.js
Labels: enhancement, FE

#111 [FIX] 새로고침할 때마다 토큰 재발급 요청
  frontend/src/index.js
  frontend/src/utils/TokenManager.js
Labels: bug, FE

#113 [Fix] spa 작동 안함
  frontend/src/component/PageComponent.js
  frontend/src/component/navigation/NavLink.js
  frontend/src/index.js
  frontend/src/pages/Home.js
  frontend/src/pages/game/Game.js
Labels: bug, FE

#115 [Feat] join room api 연결
  frontend/src/pages/game/JoinRoom.js
Labels: enhancement, FE

#116 [Design] 게임 디자인 변경
  frontend/public/object/low poly vhs textures.png
  frontend/public/object/tablePing.bin
  frontend/public/object/tablePing.gltf
  frontend/src/pages/game/PlayGame.js
  frontend/src/utils/game.js
  frontend/src/utils/game/createGameObject.js
  frontend/src/utils/game/createMap.js
  frontend/src/utils/game/eventHandler.js
  frontend/src/utils/game/game.js
  frontend/src/utils/game/gameUtils.js
Labels: FE, design

#117 [Feat] 프로필 페이지 api 연결
  frontend/public/img/profile_fallback.jpg
  frontend/src/component/contents/EditProfile.js
  frontend/src/component/contents/ProfileBattleHistory.js
  frontend/src/component/contents/ProfileItem.js
  frontend/src/component/contents/UserProfile.js
  frontend/src/component/contents/UserProfileInfo.js
  frontend/src/component/form/EditProfileForm.js
  frontend/src/component/modal/ModalComponent.js
  frontend/src/constants/Regex.js
  frontend/src/pages/Profile.js
  frontend/src/utils/Fetch.js
  frontend/src/utils/resizeImage.js
Labels: enhancement, FE

#118 Fix nignx volumn add
  backend/friends/views.py
  docker-compose.yml
  nginx/server.conf
Labels: bug, BE

#121 [Feat] 친구페이지 모달 api 연결
  frontend/src/component/contents/FriendSearchListItem.js
  frontend/src/component/contents/FriendWaitListItem.js
  frontend/src/pages/Friends.js
Labels: enhancement, FE

#124 120 be fix friend api fix
  backend/friends/models.py
  backend/friends/tests.py
  backend/friends/views.py
  backend/login/views.py
  backend/users/models.py
Labels: BE

#122 [Design] 입력받는 부분 폰트 수정, 로딩 버그 수정
  frontend/src/component/form/LoginForm.js
  frontend/src/component/form/RegisterFormItem.js
  frontend/src/pages/Friends.js
  frontend/src/pages/Home.js
  frontend/src/pages/Login.js
  frontend/src/pages/Profile.js
  frontend/src/scss/styles.scss
  frontend/src/utils/Fetch.js
Labels: bug, FE, design

#125 [BE] Chore: black formatter 적용
  backend/users/tests.py
Labels: BE, design

#130 [BE] Fix: is_authenticated flag 삭제
  backend/friends/tests.py
  backend/friends/views.py
  backend/login/tests.py
  backend/login/views.py
  backend/rooms/tests.py
  backend/users/models.py
  backend/users/tests.py
Labels: bug, BE

#132 [Feat] 게임 로직 추가
  frontend/src/utils/game/createGameObject.js
  frontend/src/utils/game/eventHandler.js
  frontend/src/utils/game/game.js
Labels: enhancement, FE

#131 [Fix] fetch patch 요청 리턴 수정, 친구 페이지 모달 버튼 이벤트 수정
  frontend/src/component/contents/FriendWaitListItem.js
  frontend/src/pages/Friends.js
  frontend/src/utils/Fetch.js
Labels: bug, FE

#143 143 be fix refresh token check fix
  backend/login/views.py
  backend/rooms/views.py
  backend/users/views.py
Labels: bug, BE

#140 [Feat] 게임 방 정보 모달
  frontend/src/component/contents/GameRoomInfo.js
  frontend/src/index.js
  frontend/src/pages/Friends.js
  frontend/src/pages/Login.js
  frontend/src/pages/game/JoinRoom.js
  frontend/src/pages/game/WaitingRoom.js
  frontend/src/scss/colors.scss
  frontend/src/scss/variables.scss
  frontend/src/utils/TokenManager.js
Labels: enhancement, FE, design

#144 [Feat] create room api 연결
  frontend/src/component/contents/GameRoomInfo.js
  frontend/src/component/form/CreateRoomForm.js
  frontend/src/constants/Regex.js
  frontend/src/pages/game/CreateRoom.js
  frontend/src/utils/Fetch.js
Labels: enhancement, FE

#147 [Fix] Create Room 페이지 에러 수정
  frontend/src/component/form/CreateRoomForm.js
  frontend/src/component/form/CreateRoomFormItem.js
Labels: bug, FE

#150 [Feat] 친구 삭제 기능 추가
  frontend/src/component/PageComponent.js
  frontend/src/component/card/FriendInfoCard.js
  frontend/src/pages/Friends.js
  frontend/src/scss/colors.scss
Labels: enhancement, FE

#152 [Fix] Friend, Profile fetch 에러 처리 추가
  frontend/src/pages/Friends.js
  frontend/src/pages/Profile.js
Labels: bug, FE

#153 [Feat] 게임 기능 추가
  frontend/src/index.html
  frontend/src/pages/game/PlayGame.js
  frontend/src/scss/styles.scss
  frontend/src/utils/game/cameraSetting.js
  frontend/src/utils/game/checkPaddleHit.js
  frontend/src/utils/game/createGameObject.js
  frontend/src/utils/game/eventHandler.js
  frontend/src/utils/game/game.js
  frontend/src/utils/game/rendering.js
  frontend/src/utils/game/sceneSetting.js
Labels: enhancement, FE
